services:
  app:
    command:
      - python
      - -m
      - uvicorn
      - motif_feedback.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --reload
      - --reload-dir
      - /app/motif_feedback
      - --no-server-header
      - --no-proxy-headers

    volumes:
      - type: bind
        source: ./motif_feedback
        target: /app/motif_feedback
        read_only: true

  runner:
    volumes:
      - type: bind
        source: ./runner/service.py
        target: /runner-app/service.py
        read_only: true
