"""Stable application defaults and hard validation ceilings.

Deployment-tunable values live on ``Settings``. Constants here name format,
schema, and safety boundaries shared by modules without loading dotenv.
"""

# Agent and project files.
AGENT_FILE_HARD_MAX_BYTES = 15_000
LOCAL_SESSION_TOKEN_BYTES = 32
PROJECT_FILE_LIST_MAX_ENTRIES = 500
PROJECT_FILE_READ_MAX_CHARS = 200_000
PROJECT_FILE_SEARCH_DEFAULT_RESULTS = 20
PROJECT_FILE_SEARCH_MAX_RESULTS = 50
PROJECT_FILE_SEARCH_SCAN_MAX_CHARS = 250_000
PROJECT_FILE_SEARCH_SNIPPET_BEFORE_CHARS = 160
PROJECT_FILE_SEARCH_SNIPPET_AFTER_CHARS = 440

# Runner request schema ceilings. Effective defaults remain lower and are
# configurable through Settings / .env.
RUNNER_ID_MIN_CHARS = 8
RUNNER_ID_MAX_CHARS = 64
RUNNER_PATH_MAX_CHARS = 500
RUNNER_ARGUMENT_HARD_MAX_COUNT = 128
RUNNER_ARGUMENT_HARD_MAX_CHARS = 4_000
RUNNER_ARGUMENTS_HARD_MAX_BYTES = 64_000
RUNNER_INPUT_HARD_MAX_BYTES = 1_000_000
RUNNER_INPUT_MESSAGE_HARD_MAX_BYTES = 64_000

# General request schema limits.
PROJECT_NAME_MAX_CHARS = 80
CHAT_MESSAGE_MAX_CHARS = 50_000
PERSONA_YAML_MAX_CHARS = 200_000
SHARED_CONTEXT_MAX_CHARS = 300_000
PROVIDER_CATALOG_YAML_MAX_CHARS = 100_000

# Runtime setup bounds.
DEFAULT_TEMPERATURE = 0.72
MIN_TEMPERATURE = 0.0
MAX_TEMPERATURE = 2.0
DEFAULT_MAX_TOKENS = 1_800
MIN_MAX_TOKENS = 128
MAX_MAX_TOKENS = 12_000

# API collection bounds.
DEFAULT_PROJECT_MESSAGE_LIMIT = 300
DEFAULT_STORAGE_MESSAGE_LIMIT = 200
MAX_PROJECT_MESSAGE_LIMIT = 1_000
DEFAULT_MEMORY_EVENT_LIMIT = 20
MAX_MEMORY_EVENT_LIMIT = 100
DEFAULT_WEB_SOURCE_LIMIT = 100
MAX_WEB_SOURCE_LIMIT = 500
MAX_PERSONA_PROPOSALS = 200
ATTRACTOR_STRENGTH_PATH_PARTS = 3
DEFAULT_MOTIF_LIMIT = 200
MAX_MOTIF_LIMIT = 500
MOTIF_OBSERVATIONS_PER_BEAT = 3
MOTIF_CONNECTION_MAX_ITEMS = 4
MOTIF_LABEL_MAX_CHARS = 96
MOTIF_DESCRIPTION_MAX_CHARS = 1_200
MOTIF_TRAJECTORY_WINDOW = 64
MOTIF_PATTERN_MIN_DISTINCT_TURNS = 3

# Storage boundaries.
SQLITE_TIMEOUT_SECONDS = 15
STORED_MESSAGE_MAX_CHARS = 8_000
STORED_MEMORY_TRIGGER_MAX_CHARS = 4_000
STORED_MEMORY_RETURN_MAX_CHARS = 8_000
STORED_MEMORY_TRIGGER_SUMMARY_MAX_CHARS = 240
STORED_MEMORY_RETURN_SUMMARY_MAX_CHARS = 800
STORED_MEMORY_QUERY_MAX_ROWS = 200
STORED_PROJECT_NAME_MAX_CHARS = PROJECT_NAME_MAX_CHARS
STORED_SOURCE_PROJECT_NAME_MAX_CHARS = 200
PROJECT_SLUG_MAX_CHARS = 48
PROJECT_ID_RANDOM_CHARS = 6

# Provider and collaboration defaults.
DEFAULT_PARTICIPATION_RETRIES = 2
DEFAULT_PROVIDER_CONNECT_TIMEOUT_SECONDS = 20.0
DEFAULT_PROVIDER_RESPONSE_MAX_BYTES = 2_000_000
DEFAULT_PROVIDER_TOOL_CALLS_PER_RESPONSE = 16
DEFAULT_PROVIDER_TOOL_CALLS_PER_TURN = 48
DEFAULT_AGENT_TURN_BEATS = 3
DEFAULT_LOCAL_MEMORY_CONTEXT_EVENTS = 8
DEFAULT_GLOBAL_MEMORY_CONTEXT_EVENTS = 6
PROVIDER_ERROR_DETAIL_MAX_CHARS = 2_000
PROVIDER_MODEL_ID_MAX_CHARS = 200
MEMORY_PROMPT_TRIGGER_MAX_CHARS = 500
MEMORY_PROMPT_RETURN_MAX_CHARS = 900
WEB_SOURCE_PROMPT_MIN_CHARS = 2_000
WEB_URL_MAX_CHARS = 2_048
WEB_CONTENT_TYPE_SAMPLE_BYTES = 100
DEFAULT_WEB_FETCH_CONNECT_TIMEOUT_SECONDS = 10
DEFAULT_WEB_FETCH_CHUNK_BYTES = 65_536
DEFAULT_WEB_FETCH_USER_AGENT = "MotifFeedback/1.0 (user-requested read-only page fetch)"
HTTP_DEFAULT_PORT = 80
HTTPS_DEFAULT_PORT = 443

# Runner client transport defaults.
DEFAULT_RUNNER_CLIENT_TIMEOUT_SECONDS = 12.0
DEFAULT_RUNNER_REQUEST_MAX_BYTES = 8_500_000
DEFAULT_RUNNER_RESPONSE_MAX_BYTES = 1_000_000
DEFAULT_RUNNER_SOCKET_POLL_SECONDS = 0.1
DEFAULT_RUNNER_SOCKET_READ_BYTES = 16_384

# Persona update boundaries.
PERSONA_CHANGE_MAX_BYTES = 16_000
PERSONA_CHANGE_MAX_DEPTH = 8
PERSONA_CHANGE_MAX_COLLECTION_ITEMS = 100
PERSONA_CHANGE_MAX_STRING_CHARS = 4_000
